version: '3'

services:
    api:
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./djangorest:/djangorest
        command: "python manage.py runserver 0.0.0.0:8000"