# Generated by Django 3.1.4 on 2021-06-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplane_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('range', models.IntegerField()),
                ('engines', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('last_updated', models.TimeField(auto_now_add=True)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_basics.status')),
            ],
        ),
    ]
